//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieDetail()
        {
            this.Casts = new HashSet<Cast>();
            this.Reviews = new HashSet<Review>();
        }
    
        public string backdrop_path { get; set; }
        public string genre { get; set; }
        public Nullable<int> budget { get; set; }
        public string overview { get; set; }
        public string poster_path { get; set; }
        public string release_date { get; set; }
        public Nullable<int> revenue { get; set; }
        public string tagline { get; set; }
        public string title { get; set; }
        public Nullable<double> vote_average { get; set; }
        public int id { get; set; }
        public Nullable<int> runtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cast> Casts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
